### ISSUE TITLE
Gftools builder not generating named instances in width axis in variable  font

### ISSUE THREAD

**Issue by mitradranirban** [googlefonts/gftools#1088]
I am generating my variable font through Google fonts workflow. 
The status portion of my config.yaml is
```
stat:
    - name: Width
      tag: wdth
      values:
      - name: Normal
        value: 100
        flags: 2
      - name: SemiExpanded
        value: 112.5
      - name: Expanded
        value: 125
      - name: ExtraExpanded
        value: 150
      - name: UltraExpanded
        value: 200
    - name: Weight
      tag: wght
      values:
      - name: Thin
        value: 100
      - name: ExtraLight
        value: 200
      - name: Light
        value: 300
      - name: Regular
        value: 400
        linkedValue: 700
        flags: 2
      - name: Medium
        value: 500
      - name: SemiBold
        value: 600
      - name: Bold
        value: 700
    - name: Slant
      tag: slnt
      values: 
      - name: Default
        value: 0
        linkedValue: 1
        flags: 2
      - name: Oblique
        value: -20
```
However when the variable font is generated, it contains all named instances along weight axis only and none along width axis
What may be wrong in my configuration?
