### ISSUE TITLE
gftools builder uses `touch` command on Windows

### ISSUE THREAD

**Issue by NightFurySL2001** [googlefonts/gftools#1096]
Not sure how it happened, but on Windows 10 22H2 build 19045.5737, gftools.exe 0.9.79, running `gftools builder config.yaml` on the following yaml file raises an error that `touch` is not available on Windows.

config.yaml:
```yaml
familyName: Font Name
buildVariable: true
buildStatic: false
buildTTF: false
buildOTF: true
autohintTTF: false
autohintOTF: false
sources:
- FontName.designspace
```

Log:
```
[1/3] buildVariable
cmd /c fontmake --output-path C:\Users\User\AppData\Local\Temp\tmp_g8i1q3p -o variable -m FontName.designspace --filter ... --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
[2/3] fix
cmd /c gftools-fix-font -o ../fonts/variable\FontName[wght].ttf C:\Users\User\AppData\Local\Temp\tmp_g8i1q3p
[3/3] cmd /c gftools-gen-stat --inplace  -- "../fonts/variable\FontName[wght].ttf" && touch C:\Users\User\AppData\Local\Temp\tmp8twpgngt.buildStatstamp
FAILED: C:/Users/User/AppData/Local/Temp/tmp8twpgngt.buildStatstamp
cmd /c gftools-gen-stat --inplace  -- "../fonts/variable\FontName[wght].ttf" && touch C:\Users\User\AppData\Local\Temp\tmp8twpgngt.buildStatstamp
Saving font to ../fonts/variable\FontName[wght].ttf
'touch' is not recognized as an internal or external command,
operable program or batch file.
ninja: build stopped: subcommand failed
```
