### ISSUE TITLE
packager: support wildcards in yaml file

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/gftools#232]
Adding wildcards will make constructing yaml files less tedious.

Currently, you have to list every file:

```
files:
  # These are some examples as comments, please modify, add, delete as necessary:
  OFL.txt: OFL.txt
  DESCRIPTION.en_us.html: DESCRIPTION.en_us.html
  FONTLOG.txt: FONTLOG.txt
  fonts/ttf/KumbhSans-Regular.ttf: KumbhSans-Regular.ttf
  fonts/ttf/KumbhSans-Bold.ttf: KumbhSans-Bold.ttf
  fonts/ttf/KumbhSans-Light.ttf: KumbhSans-Light.ttf
```

If we have wildcards:

```
files:
  # These are some examples as comments, please modify, add, delete as necessary:
  OFL.txt: OFL.txt
  DESCRIPTION.en_us.html: DESCRIPTION.en_us.html
  FONTLOG.txt: FONTLOG.txt
  fonts/ttf/*.ttf: *.ttf
```
