### ISSUE TITLE
Slim down upstream.yaml files?

### ISSUE THREAD

**Issue by davelab6** [googlefonts/gftools#233]
@graphicore we now have 2 upstream.yaml files in the central GF repo,

* https://github.com/google/fonts/blob/master/ofl/literata/upstream.yaml
* https://github.com/google/fonts/blob/master/ofl/chilanka/upstream.yaml

I'd like to propose making these more terse, and eliminate duplication with METADATA.pb files.

```yaml
# Please edit this upstream configuration for the family accordingly.
# This is a yaml formatted file.
# An "#" (number sign) denotes a comment.
# For more help see the docs at:
# https://github.com/googlefonts/gf-docs/tree/master/METADATA
```

I'm not sure we need all these comments in every file; adding it to `/README.md` or `/TRIVIA.md` would be fine, linking to 1 reference file with it all. 

```yaml
name: Literata
repository_url: https://github.com/googlefonts/literata
category: SERIF
designer: TypeTogether
```

Are these all in METADATA.pb?

```
# Choose one of: {', '.join(CATEGORIES)}
```

Bug in the template generator :)

```
files:
  # These are some examples as comments, please modify, add, delete as necessary:
  OFL.txt: OFL.txt
  DESCRIPTION.en_us.html: DESCRIPTION.en_us.html
```

Since these have a 1:1 mapping, I think it would be good to make the key implicit and therefore dropped.
