### ISSUE TITLE
Can builder handle non-canonical / custom axes for generating instances?

### ISSUE THREAD

**Issue by alexeiva** [googlefonts/gftools#348]
Builder created duplicate instances names because of non-canonical axes:

```
    stat:
     – Filename.ttf:
      - name: Rotation
        tag: ROTA
        values:
        - name: Rmin
          value: 0
        - name: Normal
          value: 1
        - name: Rmax
          value: 3
```

https://github.com/googlefonts/youtube-kids/issues/14
