### ISSUE TITLE
Packager chooses target folder based on previous location, not based on actual license information

### ISSUE THREAD

**Issue by yanone** [googlefonts/gftools#372]
I was going to PR a Khmer family called Nokora, which already exists in the catalog under Apache (no idea how it got there, as all fonts I'm currently working on are new).

The packager will always choose the `apache` folder as a target, although nothing in the source hints at an Apache License. Instead, all signs in the source suggest an OFL license.

I don't think the packager should make assumptions, but instead use my actual data.

Here’s my packager yaml:
```
name: Nokora
repository_url: https://github.com/danhhong/Nokora.git
branch: master
category: SANS_SERIF
designer: Danh Hong
files:
  OFL.txt: OFL.txt
  DESCRIPTION.en_us.html: DESCRIPTION.en_us.html
  Release/ttf/Nokora-Thin.ttf: Nokora-Thin.ttf
  Release/ttf/Nokora-Light.ttf: Nokora-Light.ttf
  Release/ttf/Nokora-Regular.ttf: Nokora-Regular.ttf
  Release/ttf/Nokora-Bold.ttf: Nokora-Bold.ttf
  Release/ttf/Nokora-Black.ttf: Nokora-Black.ttf
```
