### ISSUE TITLE
[builder] Instances key in config.yml should override axis registry

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/gftools#628]
When using Instances keys in the config.yml they should override the Axis Registry when stylenames are specified.

E.g.

```
  - familyName: "Sofia Sans Extra Condensed"
    styleName: "HairlLine"
    coordinates:
      wght: 1
```
Should produce `SofiaSansExtraCondensed-HairlLine.ttf` instead of `SofiaSansExtraCondensedHairlLine-Regular.ttf`

This would be particularly useful for fonts with new custom Axis.
