### ISSUE TITLE
gen-stat format agnostic

### ISSUE THREAD

**Issue by guidoferreyra** [googlefonts/gftools#736]
When using gen-stat from a config yml file is needed to use the complete filename including file extension eg:

```
Lora[wght].ttf:
- name: Weight
  tag: wght
  values:
  - name: Regular
    value: 400
    ...
```
I think it will be cool if the extension can be ommited so the same config declaration can be used to patch CFF variable fonts.
