### ISSUE TITLE
Builder: what syntax is needed to add custom STAT tables when using custom recipe?

### ISSUE THREAD

**Issue by arrowtype** [googlefonts/gftools#917]
I need to build a variable font with a rename operation, so I’m using the newly-released custom recipes in the builder.

However, I’m having difficulty in making the intended STAT table compile. 

I can achieve a custom STAT table without issue in a non-recipe setup, but it seems that the builder ignores the STAT info once I do add the custom recipe. When I’m using a recipe, the builder just uses Google defaults from the axisregistry. For the current family I’m building, the GF Weight axis has too many instances and slightly incorrect names, so this isn’t ideal.

Am I doing something wrong? I’ve dug around the repo and issues quite a bit, but I’m having trouble finding many specifics around the syntax of the builder `stat` option, and especially not much on using the `stat` option within a recipe. 

Here’s my current config.yaml:

```yaml
familyName: Familyname
buildVariable: false
buildStatic: false
buildWebfont: false
interpolate: true
outputDir: ./fonts
sources:
  - sources/glyphs/Familyname-Italic.glyphs
  - sources/glyphs/Familyname.glyphs
recipeProvider: googlefonts
recipe:
  fonts/variable/Familyname[wght].ttf:
    - source: sources/glyphs/Familyname.glyphs
    - args: --filter ...  --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
      operation: buildVariable
    - args: ""
      operation: fix
    - operation: rename
      name: Familyname Variable
  fonts/variable/FamilynameItalic[wght].ttf:
    - source: sources/glyphs/Familyname-Italic.glyphs
    - args: --filter ...  --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
      operation: buildVariable
    - args: ""
      operation: fix
    - operation: rename
      name: Familyname Variable
    - args: ""
      needs:
        - ./fonts/variable/Familyname[wght].ttf
      postprocess: buildStat
stat:
  - name: Weight
    tag: wght
    values:
      - name: Extra Light
        value: 200
      - name: Light
        value: 300
      - name: Regular
        value: 400
        flags: 2
      - name: Medium
        value: 500
      - name: Bold
        value: 700
      - name: Black
        value: 900
```

(In another family, I’m trying to add STAT info for a Slant axis, and the builder simply isn’t adding STAT instances for the Slant axis.)

Using `gftools-builder --generate config.yaml` was very helpful in putting together the custom recipe (discussed in https://github.com/googlefonts/gftools/issues/907), but it doesn’t seem to point me to forming my STAT info in the right way.

Any insights or pointers would be greatly appreciated. Thanks so much!

**Comment by simoncozens** [comment]
Ah. Yes, this gets complicated.

The way to think about it is that the config file is not used by the builder so much as it is used by the *recipe provider*. When you use the googlefonts recipe provider, it gets fed the config file and it turns all of your config options (`buildVariable`, for example) into steps and fontmake arguments and so on. So in the case of the `stat` entry in the config file, the recipe provider knows that it needs to dump that information out into a separate temporary file and use that temporary file as the parameters to buildStat.

But when you're using a recipe, you're on your own, no handholding - *everything else* in your config file is ignored when it comes to what needs to be done to build that particular target.

So in this case, you want to move that `stat:` entry into a separate `stat.yaml` file, call it `sources/stat.yaml` or something, and add  then have the final step of your recipe be:

```yaml
    - args: "--src sources/stat.yaml"
      needs:
        - ./fonts/variable/Familyname[wght].ttf
      postprocess: buildStat
```

**Comment by arrowtype** [comment]
Ahhh okay, that makes perfect sense. I was understanding some of that, but didn’t realize that the temp file wouldn’t work in the usual way. Thanks so much for clarifying that so well, Simon!

In case anyone else is looking at this, it took me a bit to figure out exactly how to format the `stat.yaml` file... I kept trying to start it with `stat:`, as it would be within the main `config.yaml` file, but that was failing with the message `ValueError: Filename FamilynameItalic[wght].ttf not found in stat dictionary`. This is the format that seems to work well:

```yaml
"Familyname[wght].ttf":
  - name: Weight
    tag: wght
    values:
      - name: Extra Light
        value: 200
      - name: Light
        value: 300
      - name: Regular
        value: 400
        flags: 2
      - name: Medium
        value: 500
      - name: Bold
        value: 700
      - name: Black
        value: 900
"FamilynameItalic[wght].ttf":
  - name: Weight
    tag: wght
    values:
      - name: Extra Light
        value: 200
      - name: Light
        value: 300
      - name: Regular
        value: 400
        flags: 2
      - name: Medium
        value: 500
      - name: Bold
        value: 700
      - name: Black
        value: 900
```
